image: node:16.5.0

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public

pages-branch:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mkdir -p _branch/$CI_COMMIT_BRANCH
    - cp -a dist/. _branch/$CI_COMMIT_BRANCH
  environment:
    name: $CI_COMMIT_BRANCH
    url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/_branch/$CI_COMMIT_BRANCH/index.html"
  artifacts:
    paths:
      - _branch
  except:
    - master